name: DL_ASLR_ENV
channels:
  - pytorch
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pytorch
  - torchaudio
  - torchvision
  - pip
  - pip:
    - torchsummary